### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-cgonzaru#1]
Hi @cgonzaru  !!!

Here you have some tips to improve the exercise:

- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background color
- [x] The main title should be vertically and horizontally centered (should we use Flex to achieve this?)
- [x] Avoid uppercase/capital on HTML texts, we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Finish the main title styles: words should jump and the typography is bolder
Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margins, padding...
- add cosmetic styles: color, background color...

Then repeat the same with the main content.

Let me know if you have any doubts ;)

Go for it!!

**Comment by cgonzaru** [comment]
@oneeyedman done!
